name: lcc_with_crf
pretrained_model_path: thesis/data/models/layer_comparison_classifier_haluleval_11_39__12_05_2025.pth

## Model parameters
num_classes: 1
comparison_method: cosine
aggregation_method: flattend_aggregation
final_classifier_non_linear: False
layer_depth: 2