name: average_positional_runs
positional_task: True
tag_scheme: IO

number_of_runs: 1

use_pipeline: False
freeze_lcc: False
use_pretrained: False
use_downsampling: False
#method 
training_params:
  learning_rate: 0.001
  epochs: 100
  batch_size: 100
  weight_decay: 0.01
  
  use_contrastive_loss: False
  use_cross_entropy_weighting: False
  save_model: False
  early_stopping: True
  patience: 5
  downsampling_ratio: 0.5
  crf_loss_use_cross_entropy: False