name: train_positional_layer_fusion 

tag_scheme: IO

#method 
training_params:
  learning_rate: 0.001
  epochs: 1
  batch_size: 100
  weight_decay: 0.01
  
  use_contrastive_loss: False
  use_cross_entropy_weighting: False
  save_model: False
  early_stopping: True
  patience: 100

use_pretrained: False