defaults:
  - benchmark: refact
  - llm: gemma_small
  - task: train_classifier

#dataset

use_wandb: False
seed: 42


#dataset
pca:
  use_pca: False
  n_components: 100
  layer_wise: False

use_coveig: False




hydra:
  run:
    dir: .