defaults:
  - benchmark: refact
  - llm: llama_3.1_8.yaml
  - model: layer_comparison_classifier 
  - task: ???


wandb:
  use_wandb: False
  project_name: thesis
  group_name: None
  name: 
  

#dataset

seed: 42
use_network_mounted: False

#dataset
pca:
  use_pca: False
  n_components: 100
  layer_wise: False

use_coveig: False




hydra:
  run:
    dir: .