defaults:
  - benchmark: refact
  - llm: gemma_small
  - model: layer_fusion 
  - task: ???


wandb:
  use_wandb: False
  project_name: thesis
  group_name: None
  name: 
  

#dataset

seed: 42


#dataset
pca:
  use_pca: False
  n_components: 100
  layer_wise: False

use_coveig: False




hydra:
  run:
    dir: .